### ISSUE TITLE
手工分类？

### ISSUE THREAD

**Issue by moxuec** [aaronshan/12306-captcha#4]
可不可以这样。比如：提示“档案袋”，如果一张图在“档案袋”多次出现，就给这张图加入‘档案袋’标签

**Comment by aaronshan** [comment]
@646420882 
其实在实际应用中，我们会从百度/搜狗/谷歌等图片搜索引擎中抓取图片数据，比如给定关键词档案袋，就可以爬取出很多结果。然后再对图片做处理，这样会比从12306抓取并裁剪分类快很多。
这个项目本身就是个demo，不是完整的工程应用。所以你可以根据自己的需求完善它。

**Comment by xueyeshengdan** [comment]
不会查水表吗😂

**Comment by aaronshan** [comment]
@xueyeshengdan 所以没有开源训练好的模型啊，识别原理本身已经不是秘密了。
